name: Trigger auto deployment for c4app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/c4app-AutoDeployTrigger-fa7f2e57-a3ea-45ef-ac72-b74c2091eb2c.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: connect4reg.azurecr.io
          username: ${{ secrets.C4APP_REGISTRY_USERNAME }}
          password: ${{ secrets.C4APP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: connect4reg.azurecr.io/c4app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.C4APP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n c4app -g C4ContainerApp --server connect4reg.azurecr.io --username  ${{ secrets.C4APP_REGISTRY_USERNAME }} --password ${{ secrets.C4APP_REGISTRY_PASSWORD }}
            az containerapp update -n c4app -g C4ContainerApp --image connect4reg.azurecr.io/c4app:${{ github.sha }}
